export const ADD_COMMENT = 'ADD_COMMENT'; //FOR ADDING NEW COMMENTS

export const DISHES_LOADING = 'DISHES_LOADING';//FOR LOADING DISHES
export const DISHES_FAILED = 'DISHES_FAILED';//IF DISHIES LOADING FAILED
export const ADD_DISHES = 'ADD_DISHES';//IF DISHES LOADING DONE FETCH DISHES

export const ADD_COMMENTS = 'ADD_COMMENTS';//FETCH COMMENTS
export const COMMENTS_FAILED = 'COMMENTS_FAILED';//IF FETCHING COMMENTS FAILED

export const PROMOS_LOADING = 'PROMOS_LOADING';//FOR LOADING PROMOTIONS
export const ADD_PROMOS = 'ADD_PROMOS';//FOR ADDING PROMOTIONS
export const PROMOS_FAILED = 'PROMOS_FAILED';//IF PROMOTION FETCHING FAILED
