export const ADD_COMMENT = 'ADD_COMMENT'; //FOR ADDING NEW COMMENTS

export const DISHES_LOADING = 'DISHES_LOADING';//FOR LOADING DISHES
export const ADD_DISHES = 'ADD_DISHES';//IF DISHES LOADING DONE FETCH DISHES
export const DISHES_FAILED = 'DISHES_FAILED';//IF DISHIES LOADING FAILED

export const ADD_COMMENTS = 'ADD_COMMENTS';//FETCH COMMENTS
export const COMMENTS_FAILED = 'COMMENTS_FAILED';//IF FETCHING COMMENTS FAILED

export const PROMOS_LOADING = 'PROMOS_LOADING';//FOR LOADING PROMOTIONS
export const ADD_PROMOS = 'ADD_PROMOS';//FOR ADDING PROMOTIONS
export const PROMOS_FAILED = 'PROMOS_FAILED';//IF PROMOTION FETCHING FAILED

export const LEADERS_LOADING = 'LEADERS_LOADING';//FOR LOADING LEADERS
export const ADD_LEADERS = 'ADD_LEADERS';//FOR ADDING LEADERS
export const LEADERS_FAILED = 'LEADERS_FAILED'//IF LEADERS FETCHING FAILED

export const LOGIN_REQUEST = 'LOGIN_REQUEST';//FOR LOGIN REQUEST
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';//FOR LOGIN SUCCESS
export const LOGIN_FAILURE = 'LOGIN_FAILURE';//IF LOGIN FAILED

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';//FOR LOGOUT REQUEST
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';//FOR LOGOUT SUCCESS
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';//IF LOGOUT FAILED

export const FAVORITES_LOADING = 'FAVORITES_LOADING';//FOR FAVORITES LOGING
export const FAVORITES_FAILED = 'FAVORITES_FAILED';//IF FAVORITE FAILED
export const ADD_FAVORITES = 'ADD_FAVORITES';//FOR ADDING FAVORITE